server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zfhczc.springcloud.entities

eureka:
  client:
    # 将自己注册进 EurekaServer?
    register-with-eureka: true
    # 从 EurekaServer 抓取已有的注册信息？
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
